# -*- coding: utf-8 -*-
"""
Created on Wed Nov 13 17:33:49 2024

Author: Lucía Lopez
Florencia D. Choque 
Description:
This script processes experimental pMINFLUX data using fitted point spread functions (PSFs) and TCSPC data.
At this stage, the MINFLUX excitation pattern has already been aligned, and the distances between the minima of the pattern 
have been confirmed to be good enough after a fitting process. 
This alignment and quality check are performed using `analise_EBP`, which operates on the raw PSFs generated by the MINFLUX setup.

Recommendations:
- Verify the τ parameter values, as they correspond to the peaks in the relative time histogram. 
Any hardware changes, such as swapping cables, may alter these values, potentially introducing errors. 
Future versions should automate this calibration to enhance robustness.

Details:
- An offset is applied to the relative time histogram peaks to match the acquisition order of the setup's PSFs.
- The `lifetime_win_i` and `lifetime_win_f` parameters specify the time window used for photon counting.

Note:
This code still requires adaptation for tracking experiments using Swabian hardware. But so far this is our working version.

"""

import os
import copy
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from matplotlib.patches import Ellipse
from PIL import Image
from natsort import natsorted
from pathlib import Path
from scipy.optimize import curve_fit
from hmmlearn.hmm import GaussianHMM
from sklearn.mixture import GaussianMixture
from loc_tools import indexToSpace, crb_minflux, loc_trace_minflux
from configvar import (
    TCSPC_TIME_OFFSET_NS,
    LASER_PERIOD_NS,
    NUM_PULSES,
    STEP_NM,
    LIFETIME_WIN_BEG_NS,
    LIFETIME_WIN_END_NS,
    PSF_DIR_BASE,
    DATA_DIR_BASE,
    LOCS_FILE_SUFFIX,
    SIGMA_TOL_OUTLIERS
)

plt.close('all')


date = '20250214'
tcspc_filename = 'clock_20250214-152357_.npy'
#tcspc_filename = 'psf_center0_fit_and_move_100px_20250220-204338_.npy'
bckg_filename = 'bead_bkg_20250220-205458_.npy'
psf_dir = PSF_DIR_BASE / date
data_dir = DATA_DIR_BASE / date
tcspc_file = data_dir / tcspc_filename
bckg_file = data_dir / bckg_filename
τ = np.array([0.98, 13.8, 26.12, 39.1])  # [ns] 
timetrace_bin_width_s = 0.1
target_n_ph = 1000

def gauss(x, a, mu, sigma):
    return a * np.exp(-((x - mu) ** 2) / (2 * sigma ** 2))

def bi_gaussian(coords, A1, x1, y1, sx1, sy1, A2, x2, y2, sx2, sy2):
    x, y = coords
    g1 = A1 * np.exp(-((x - x1) ** 2) / (2 * sx1 ** 2) - ((y - y1) ** 2) / (2 * sy1 ** 2))
    g2 = A2 * np.exp(-((x - x2) ** 2) / (2 * sx2 ** 2) - ((y - y2) ** 2) / (2 * sy2 ** 2))
    return g1 + g2

class EBP():
    def __init__(self, psf_dir: Path):
        self.psf_dir = psf_dir
        self.psf_colors = ['blue', 'orange', 'gray', 'yellow']
        self.psf_fits, self.pos_mins_nm, self.pos_mins_centered_nm = self.open_psf()
        self.plot_psf()

    def open_psf(self):
        """
        This function opens the specified data folder, reads in natural alphabetic order all the .npy
        files, which should contain the numpy arrays of the experimental PSFs, and loads them
        """
        psf_fit_list = []
        pos_min_nm_list = []
        for filepath in natsorted(self.psf_dir.iterdir()):
            if filepath.is_file():
                if filepath.suffix == '.npy':
                    psf_fit = np.load(filepath)
                    psf_fit_list.append(psf_fit)
                    psf_size = np.shape(psf_fit)[1]
                    self.size_nm = psf_size * STEP_NM
                    pos_min_nm = indexToSpace(
                        np.unravel_index(np.argmin(psf_fit, axis=None),psf_fit.shape),
                        self.size_nm,
                        STEP_NM
                    )
                    pos_min_nm_list.append(pos_min_nm)

        psf_fit_arr = np.array(psf_fit_list)
        pos_min_nm_arr = np.array(pos_min_nm_list)
        pos_min_nm_centered_arr = copy.deepcopy(pos_min_nm_arr)
        for min_idx in range(len(pos_min_nm_centered_arr)):
            pos_min_nm_centered_arr[min_idx][0] -= pos_min_nm_arr[0][0]
            pos_min_nm_centered_arr[min_idx][1] -= pos_min_nm_arr[0][1]  
            
        return psf_fit_arr, pos_min_nm_arr, pos_min_nm_centered_arr
    
    def plot_psf(self):
        """
        This function plots the individual experimental PSFs and the EBP
        """
        # Plot PSFs with minima positions
        fig, axes = plt.subplots(2, 2, figsize=(8, 8))
        for i, ax in enumerate(axes.flat):
            ax.set(xlabel = 'x (nm)', ylabel= 'y (nm)')
            ax.imshow(self.psf_fits[i], cmap='viridis', origin='lower')
            ax.scatter(*self.pos_mins_nm[i],
                        color=self.psf_colors[i], s=100)
            ax.set_title(f'Fitted PSF {i + 1}', fontsize=10)
        plt.tight_layout()

        #Plot EBP
        x_min, y_min = self.pos_mins_centered_nm[:, 0], self.pos_mins_centered_nm[:, 1]
        plt.figure('EBP')
        for i in range(len(self.pos_mins_centered_nm)):
            plt.scatter(x_min[i]- self.pos_mins_centered_nm[0][0], y_min[i] - self.pos_mins_centered_nm[0][1], c=self.psf_colors[i], label=f'{i+1}')
        plt.title('EBP')
        plt.xlabel('x (nm)')
        plt.ylabel('y (nm)')
        plt.axhline(0, color='gray', linestyle='--', linewidth=0.5)
        plt.axvline(0, color='gray', linestyle='--', linewidth=0.5)
        plt.legend()
        plt.axis("equal")
        plt.grid(True)
        plt.show()

class TCSPCData():
    def __init__(self, tcspc_data_path: Path, bckg_data_path: Path, timetrace_bin_width_s: float, τ: list):
        self.tcspc_data_path = tcspc_data_path
        self.bckg_data_path = bckg_data_path
        self.timetrace_bin_width_s = timetrace_bin_width_s
        self.τ = τ
        # get folder and filename of the tcspc data file
        self.tcspc_data_dir = self.tcspc_data_path.parent
        self.tcspc_data_filename = self.tcspc_data_path.stem
        # load TCSPC data, plot timetrace and ask if there is a photobleaching step
        self.abs_time_s, self.rel_time_ns = self.load_tcspc_data(self.tcspc_data_path)
        self.tot_t_measuring_s = (self.abs_time_s.max() - self.abs_time_s.min())
        self.plot_timetrace()
        self.ask_analysis_type()
        # if there is no photobleaching step, gets background data from separate file
        if not self.is_single_mol:
            self.bckg_abs_time_s, self.bckg_rel_time_ns = self.load_tcspc_data(self.bckg_data_path)
            self.tot_t_measuring_bckg_s = (self.bckg_abs_time_s.max() - self.bckg_abs_time_s.min())
        # process and show data
        self.filter_time_data()
        self.shift_and_plot_tcspc_data()
        self.prep_ph_foranalysis()
        
    def load_tcspc_data(self, data_path):
        """
        This function loads the TCSPC data from a .npy file, loading both the absolute and relative times
        of the events
        """
        all_data = np.load(data_path)
        rel_time_ps = all_data[2,:]
        abs_time_ps_woffset = all_data[1,:]
        abs_time_s = (abs_time_ps_woffset - abs_time_ps_woffset.min()) / 1e12 # ps to s and eliminate offset
        rel_time_ns = rel_time_ps * 1e-3
        return abs_time_s, rel_time_ns

    def plot_timetrace(self):
        """
        This function plots the intensity time trace of the measurement
        """
        plt.figure("Histogram abs_time")
        self.raw_timetrace_bin_edges = np.arange(0, self.tot_t_measuring_s + self.timetrace_bin_width_s, self.timetrace_bin_width_s)
        self.raw_timetrace_counts_hz, _, _ = plt.hist(self.abs_time_s, bins=self.raw_timetrace_bin_edges, alpha=0.7, color='blue', weights=np.ones_like(self.abs_time_s) / self.timetrace_bin_width_s)
        plt.xlabel("Time [s]")
        plt.ylabel("Counts [Hz]")
        plt.title("Time trace")
        plt.tight_layout()
        plt.show()
        
    def ask_analysis_type(self):
        """
        This function asks the user whether the measurement presents a photobleaching step or not. If yes, the background will be extracted
        from the measurement itself, after the photobleaching steps. Otherwise, a separate background file will be loaded.
        """
        is_there_photobleach = input("Does the measurement present a photobleaching step? (y/n) ")
        if is_there_photobleach == 'y':
            self.is_single_mol = True
        else:
            self.is_single_mol = False
        
    def filter_time_data(self):
        """
        This function asks the user the start and end time to select the relevant part of the measurement
        to be analysed, and filter all the data using these parameters and the relative time windows.
        If it is a single molecule, it also asks for an intensity threshold to identify the photobleaching step
        as the last moment the molecule goes below the intensity threshold and never recovers.
        Finally, it computes the emitter and background counts and average SBR.
        """
        start_t_input = input("Start time for analysis in s (input nothing for 0): ")
        if not start_t_input:
            self.start_t_s = 0.0
        else:
            self.start_t_s = float(start_t_input)
        end_t_input = input("End time for analysis in s (input nothing for end of the trace): ")
        if not end_t_input:
            self.end_t_s = self.tot_t_measuring_s
        else:
            self.end_t_s = float(end_t_input)
        # if it is a single molecule, asks for intensity threshold to identify the photobleaching step and filter data based on that
        if self.is_single_mol:
            int_threshold = float(input("Intensity threshold for signal in Hz: "))
            # find all the bin (left) edges where the molecule intensity is below the threshold
            dark_bin_edges = self.raw_timetrace_bin_edges[:-1][self.raw_timetrace_counts_hz < int_threshold]
            # compute times until two nearest dark bins. The n-th element is the time between the (n-1)-th and the n-th dark bin
            t_tonext_dark_bin = np.concatenate(([dark_bin_edges[0]], np.diff(dark_bin_edges)))
            # find the first bin of each dark period of the molecule
            start_dark_time = dark_bin_edges[t_tonext_dark_bin > (self.timetrace_bin_width_s * 1.5)]
            # the bleaching step is selected as the last time the molecule goes dark and never recovers
            self.bleach_t_s = start_dark_time[-1]
            print(f"Molecule photobleached after {self.bleach_t_s} s")
            self.emitter_stop_t_s = self.bleach_t_s - self.timetrace_bin_width_s
            self.bckg_start_t_s = self.bleach_t_s + self.timetrace_bin_width_s
            self.tot_t_measuring_bckg_s = self.tot_t_measuring_s - self.bckg_start_t_s
        else: 
            # if there is not photobleaching step, counts are considered until the end of the measurement
            self.emitter_stop_t_s = self.tot_t_measuring_s
            
        # here filter the data based on the start and end time selected by the user
        self.filt_rel_time_ns = self.rel_time_ns[np.logical_and(
            self.abs_time_s > self.start_t_s,
            self.abs_time_s < np.min((self.end_t_s, self.emitter_stop_t_s))
        )]
        self.filt_abs_time_s = self.abs_time_s[np.logical_and(
            self.abs_time_s > self.start_t_s,
            self.abs_time_s < np.min((self.end_t_s, self.emitter_stop_t_s))
        )]
        # only if it is a single molecule, gets the background counts from the measurement itself, after photobleaching
        if self.is_single_mol:
            self.bckg_rel_time_ns = self.rel_time_ns[self.abs_time_s > self.bckg_start_t_s]
            self.bckg_abs_time_s = self.abs_time_s[self.abs_time_s > self.bckg_start_t_s]
        self.photons_tokeep = len(self.filt_abs_time_s)
        
        print(f"Total number of detected photons in the relevant part of the measurement: {self.photons_tokeep}")
        self.avg_bckg_counts = len(self.bckg_abs_time_s) / self.tot_t_measuring_bckg_s
        self.avg_emitter_counts = self.photons_tokeep / (np.min((self.end_t_s, self.emitter_stop_t_s)) - self.start_t_s) - self.avg_bckg_counts
        self.avg_sbr_notimegating = self.avg_emitter_counts / self.avg_bckg_counts
        print("*****************************")
        print("Measure parameters before TCSPC timegating:")
        print(f"Average signal counts: {self.avg_emitter_counts} Hz")
        print(f"Average background counts: {self.avg_bckg_counts} Hz")
        print(f"Average SBR: {self.avg_sbr_notimegating}")
        print("*****************************")
        
    def shift_and_plot_tcspc_data(self):
        """
        This function plots the decay curves of the TCSPC data, with and without translation, and the time windows used for analysis.
        """
        # shift TCSPC data (filtered, unfiltered and background) to put first pulse close to 0
        self.rel_time_shift_ns = (self.rel_time_ns - TCSPC_TIME_OFFSET_NS) % LASER_PERIOD_NS
        self.filt_rel_time_shift_ns = (self.filt_rel_time_ns - TCSPC_TIME_OFFSET_NS) % LASER_PERIOD_NS
        self.bckg_rel_time_shift_ns = (self.bckg_rel_time_ns - TCSPC_TIME_OFFSET_NS) % LASER_PERIOD_NS
        
        plt.figure('Emitter TCSPC Histogram')
        plt.hist(self.filt_rel_time_shift_ns, bins = 300, range=(0,50), label='arrival time (shifted)', alpha=0.7)
        for tau in τ:
            plt.axvline(tau, color='red', linestyle='--')
            plt.axvspan(tau + LIFETIME_WIN_BEG_NS, tau + LIFETIME_WIN_END_NS, color='red', alpha=0.2)
        plt.xlabel('Time [ns]')
        plt.ylabel('Counts')
        plt.legend()
        plt.tight_layout()
        plt.show()
        
        plt.figure('Background TCSPC Histogram')
        plt.hist(self.bckg_rel_time_shift_ns, bins = 300, range=(0,50), label= 'arrival time (shifted)', alpha=0.7)
        for tau in τ:
            plt.axvline(tau, color='red', linestyle='--')
            plt.axvspan(tau + LIFETIME_WIN_BEG_NS, tau + LIFETIME_WIN_END_NS, color='red', alpha=0.2)
        plt.xlabel('Time [ns]')
        plt.ylabel('Counts')
        plt.legend()
        plt.tight_layout()
        plt.show()
        
    def prep_ph_foranalysis(self):
        """
        This function prepares, for each pulse, an array of absolute times keeping only the photons in the TCSPC timegating window
        which will be used for analysis. Also, it computes the corrected background counts and sbr using timegating
        """
        self.abs_time_s_foranalysis_perpulse = []
        self.bckg_counts_timegated_perpulse = np.empty(NUM_PULSES, dtype=float)
        self.tot_counts_timegated = 0

        for pulse_idx in range(NUM_PULSES):
            # computing start and end of the time window used for timegating for the current pulse
            start_win = τ[pulse_idx] + LIFETIME_WIN_BEG_NS
            end_win = τ[pulse_idx] + LIFETIME_WIN_END_NS
            # selecting all the photons used for analysis for the current pulse
            abs_time_s_foranalysis = self.filt_abs_time_s[
                np.logical_and(
                    self.filt_rel_time_shift_ns > start_win,
                    self.filt_rel_time_shift_ns < end_win,
                )
            ]
            self.tot_counts_timegated += len(abs_time_s_foranalysis) / (np.min((self.end_t_s, self.emitter_stop_t_s)) - self.start_t_s)
            # appending (important: a deepcopy!) of the obtained array to the list
            self.abs_time_s_foranalysis_perpulse.append(copy.deepcopy(abs_time_s_foranalysis))
            # now doing the same with the background to get the correct background counts
            self.bckg_counts_timegated_perpulse[pulse_idx] = len(self.bckg_abs_time_s[
                np.logical_and(
                    self.bckg_rel_time_shift_ns > start_win,
                    self.bckg_rel_time_shift_ns < end_win,
                )
            ]) / self.tot_t_measuring_bckg_s
        self.bckg_counts_timegated = np.sum(self.bckg_counts_timegated_perpulse)
        # total emitter photons used for analysis
        self.emitter_counts_timegated = self.tot_counts_timegated - self.bckg_counts_timegated
        # real SBR
        self.sbr_timegated = self.emitter_counts_timegated / self.bckg_counts_timegated
            
        print("*****************************")
        print("Measure parameters after TCSPC timegating:")
        print(f"Signal counts used for analysis: {self.emitter_counts_timegated}")
        print(f"Background counts for all pulses: {self.bckg_counts_timegated}")
        print(f"Average SBR with timegating: {self.sbr_timegated}")
        print("*****************************")

class MINFLUXAnalysis():
    def __init__(self, ebp: EBP, tcspc_data: TCSPCData, target_n_ph: int):
        self.ebp = ebp
        self.tcspc_data = tcspc_data
        self.target_n_ph = target_n_ph
        self.choose_locs_t_binning()
        self.calc_ph_perloc_perpulse()
        self.localizations = self.minflux_localize()
        self.save_locs()
        
    def choose_locs_t_binning(self):
        """
        this function allows the user to choose the time binnin used for MINFLUX localizations
        """
        target_locs_t_binning_s = float(self.target_n_ph) / self.tcspc_data.tot_counts_timegated
        print(f"Localization time binning (in s) to obtain {self.target_n_ph} photons per bin: {target_locs_t_binning_s}")
        self.locs_t_binning_s = float(input("Choose localization time binning (in s): "))
        self.avg_n_ph_perloc = self.tcspc_data.tot_counts_timegated * self.locs_t_binning_s
        print(f"Average number of photons per localization: {self.avg_n_ph_perloc}")
        # compute background photons per localization bin, per pulse
        self.bckg_ph_perloc_perpulse = np.empty(NUM_PULSES, dtype=float)
        for pulse_idx in range(NUM_PULSES):
            self.bckg_ph_perloc_perpulse[pulse_idx] = self.tcspc_data.bckg_counts_timegated_perpulse[pulse_idx] * self.locs_t_binning_s
            print(f"Expected background photons per localization for pulse {pulse_idx + 1}: {self.bckg_ph_perloc_perpulse[pulse_idx]}")
        
    def calc_ph_perloc_perpulse(self):
        """
        This function computes the histograms of the counts for each localization bin and for all pulses separately and
        alltogether, and the SBR for each localization
        """
        # compute histograms of photons for each pulse using the chosen time binning
        self.locs_bin_edges = np.arange(self.tcspc_data.start_t_s, self.tcspc_data.emitter_stop_t_s, self.locs_t_binning_s)
        print(f"Total number of localizations: {len(self.locs_bin_edges) - 1}")
        self.ph_perloc_perpulse = np.empty((NUM_PULSES, len(self.locs_bin_edges) - 1), dtype=int)
        for pulse_idx in range(NUM_PULSES):
            self.ph_perloc_perpulse[pulse_idx, :], _ = np.histogram(self.tcspc_data.abs_time_s_foranalysis_perpulse[pulse_idx], self.locs_bin_edges)
        self.ph_perloc_allpulses = np.sum(self.ph_perloc_perpulse, axis=0)
        # Now compute the SBR for each individual localization by dividing the number of photons of each bin for the expected number of background
        # photons in the same time interval
        self.sbr_perloc = copy.deepcopy(self.ph_perloc_allpulses) / np.sum(self.bckg_ph_perloc_perpulse) - 1
        
    def minflux_localize(self):
        """
        This function calls numba optimized functions to compute MINFLUX localizations for the selected part of the trace
        """
        locs_coords = loc_trace_minflux(self.ph_perloc_perpulse, self.bckg_ph_perloc_perpulse, self.sbr_perloc, self.ebp.psf_fits, STEP_NM)
        return np.concatenate((
                self.locs_bin_edges[:-1].reshape(-1,1),
                locs_coords,
                self.ph_perloc_allpulses.reshape(-1,1), 
                self.sbr_perloc.reshape(-1,1)
            ), axis=1)
       
    def save_locs(self):
        """
        This function save the localizations as a .npy file, to be accessed and used for post-processing
        """
        self.locs_results_filename = (self.tcspc_data.tcspc_data_filename + LOCS_FILE_SUFFIX + 'from' + str(int(self.tcspc_data.start_t_s)) +
                                      'to' + str(int(self.tcspc_data.end_t_s)) + 's_' + str(int(self.locs_t_binning_s * 1e3)) + 'ms_binning.npy')
        self.locs_results_filepath = self.tcspc_data.tcspc_data_dir / self.locs_results_filename
        np.save(self.locs_results_filepath, self.localizations)

class DataPostProcessor():
    def __init__(self, locs_filepath: Path, ebp: EBP, bin_size: int):
        self.locs_filepath = locs_filepath
        self.ebp = ebp
        self.bin_size = bin_size
        
        # open file containing localization results
        self.locs = self.load_locs(self.locs_filepath)
        # eliminate spatial outliers from localizations
        self.locs_nooutliers = self.eliminate_outliers(self.locs)
        # now filter localizations based on photons numbers
        self.locs_filt = self.filter_locs_forph(self.locs_nooutliers)
        # compute average photon number and SBR based on filtered localizations
        self.avg_ph_perloc, self.avg_sbr = self.get_avg_loc_param(self.locs_filt)
        # compute and plot CRB map, superimposed with EBP
        self.calc_crb(self.avg_ph_perloc, self.avg_sbr)
        self.plot_crb_andebp()
        # recenter localizations
        self.locs_centered = self.center_locs(self.locs_filt)
        # get range for future plots
        self.x_plot_range, self.y_plot_range = self.get_glob_plots_limits(self.locs_centered)
        # all plots
        self.plot_locs_timecoded_withebp(self.locs_centered)
        self.plot_loc_density_withebp(self.locs_centered)
        self.plot_locs_withcrb(self.locs_centered)
        
    def load_locs(self, locs_filepath):
        """
        This function loads the localization array saved as a .npy
        """
        locs = np.load(locs_filepath)
        self.avg_ph_perloc = np.mean(locs[:,3])
        self.sigma_ph_perloc = np.std(locs[:,3])
        print(f"Average number of photons per localization: {self.avg_ph_perloc} \u00B1 {self.sigma_ph_perloc}")
        return locs
        
    def eliminate_outliers(self, locs):
        """
        This function eliminates all localization exceeding 3 sigma from the center of mass
        """
        self.average_coords_locs = (
            np.mean(locs[:, 1]),
            np.mean(locs[:, 2])
        )
        self.average_sigma_locs = (
            np.std(locs[:, 1]),
            np.std(locs[:, 2])
        )
        dists_loc_from_center = np.sqrt(
            (locs[:, 1] - self.average_coords_locs[0])**2 + (locs[:, 2] - self.average_coords_locs[1])**2
        )
        locs_nooutliers = locs[dists_loc_from_center < SIGMA_TOL_OUTLIERS * np.sqrt(self.average_sigma_locs[0]**2 + self.average_sigma_locs[1]**2)]
        return locs_nooutliers
        
    def filter_locs_forph(self, locs):
        """This function filters out localizations obtained with less photons than a chosen threshold"""
        min_ph_perloc_input = input("Minimum number of photons required for a single localization (no input for no filtering): ")
        if min_ph_perloc_input:
            self.min_ph_perloc = float(min_ph_perloc_input)
        else:
            self.min_ph_perloc = 0
        locs_filtered = locs[locs[:, 3] >= self.min_ph_perloc]
        return locs_filtered
        
    def get_avg_loc_param(self, locs):
        """
        This function computes the average number of photons and SBR for the remaining localizations
        """
        avg_ph_perloc = np.mean(locs[:, 3])
        avg_sbr = np.average(locs[:, 4], weights=locs[:, 3])
        return avg_ph_perloc, avg_sbr
        
    def center_locs(self, locs):
        """
        This function changes system of reference for the localizations, cenetering their values in the minimum of the first beam
        """
        locs_centered = copy.deepcopy(locs)
        locs_centered[:, 1] -= self.ebp.pos_mins_nm[0][0]
        locs_centered[:, 2] -= self.ebp.pos_mins_nm[0][1]
        return locs_centered
        
    def get_glob_plots_limits(self, locs):
        """
        This function computes the limit in x and y for plots to keep the size of the plotted area consistent
        """
        x_ebp_range = (
            min(self.ebp.pos_mins_centered_nm, key=lambda elem: elem[0])[0],
            max(self.ebp.pos_mins_centered_nm, key=lambda elem: elem[0])[0]
        )
        y_ebp_range = (
            min(self.ebp.pos_mins_centered_nm, key=lambda elem: elem[1])[1],
            max(self.ebp.pos_mins_centered_nm, key=lambda elem: elem[1])[1]
        )
        x_filt_locs_range = (np.min(locs[:, 1]), np.max(locs[:, 1]))
        y_filt_locs_range = (np.min(locs[:, 2]), np.max(locs[:, 2]))
        x_global_range = (np.min((x_ebp_range[0], x_filt_locs_range[0])), np.max((x_ebp_range[1], x_filt_locs_range[1])))
        y_global_range = (np.min((y_ebp_range[0], y_filt_locs_range[0])), np.max((y_ebp_range[1], y_filt_locs_range[1])))
        # add a 10% padding
        x_plot_range = (x_global_range[0] - 0.1 * (x_global_range[1] - x_global_range[0]), x_global_range[1] + 0.1 * (x_global_range[1] - x_global_range[0]))
        y_plot_range = (y_global_range[0] - 0.1 * (y_global_range[1] - y_global_range[0]), y_global_range[1] + 0.1 * (y_global_range[1] - y_global_range[0]))
        return x_plot_range, y_plot_range
                    
    def calc_crb(self, ph_perloc, sbr):
        """
        This function computes the crb based on the experimental SBR and average photon number (averaging x and y errors)
        """
        self.σ_CRB = crb_minflux(NUM_PULSES, self.ebp.psf_fits, sbr, STEP_NM, self.ebp.size_nm, ph_perloc, method='1')
     
    def plot_crb_andebp(self):
        """
        This function plots the CRB map alone
        """
        # Create the CRB plot with the same extent as the scatter plots
        plt.figure('CRB_map')
        # Shift CRB map by the same amount as the EBP
        plt.imshow(
            self.σ_CRB, cmap='viridis', vmin=0, vmax=20,
            extent=(
                - self.ebp.pos_mins_nm[0][0] - 0.5, self.σ_CRB.shape[1] - self.ebp.pos_mins_nm[0][0] - 0.5,
                - self.ebp.pos_mins_nm[0][1] - 0.5, self.σ_CRB.shape[0] - self.ebp.pos_mins_nm[0][1] - 0.5
            ),
            origin='lower'
        )
        plt.colorbar(label='σ_CRB Value')

        # Plot PSF minima positions with the same color mapping as before
        for beam_idx, min_pos in enumerate(self.ebp.pos_mins_centered_nm):
            plt.scatter(*min_pos, color=self.ebp.psf_colors[beam_idx], s=100)

        # Ensure the axes and aspect ratio are the same as in scatter plots
        plt.gca().set_aspect('equal')
        plt.xlabel('x (nm)')
        plt.ylabel('y (nm)')
        plt.title('σ_CRB with Aligned Reference Frame')
        plt.tight_layout()
        plt.show()
                        
    def plot_locs_timecoded_withebp(self, locs):
        """
        This function plots all (filtered) localizations, encoding with time, superposed with the EBP
        """
        plt.figure('Time-encoded localizations')
        for beam_idx, min_pos in enumerate(self.ebp.pos_mins_centered_nm):
            plt.scatter(*min_pos, color=self.ebp.psf_colors[beam_idx], s=100)
        plt.scatter(locs[:, 1], locs[:, 2], c=range(len(locs[:, 0])), cmap='rainbow', s=20, alpha=0.2)
        plt.xlim(self.x_plot_range)
        plt.ylim(self.y_plot_range)
        # Annotations
        plt.gca().set_aspect('equal'), plt.xlabel('x (nm)'), plt.ylabel('y (nm)'), plt.tight_layout()
        plt.show()
        
    def plot_loc_density_withebp(self, locs):
        """
        This function produces the 2D histogram of the localization density, superposed with the EBP
        """
        bin_x_edges = np.arange(int(self.x_plot_range[0]), int(self.x_plot_range[1]) + self.bin_size, self.bin_size)
        bin_y_edges = np.arange(int(self.y_plot_range[0]), int(self.y_plot_range[1]) + self.bin_size, self.bin_size)
        loc_dens_hist, _, _ = np.histogram2d(locs[:, 1], locs[:, 2], bins=(bin_x_edges, bin_y_edges))
        max_loc_dens = np.max(loc_dens_hist)
        plt.figure('Localization density')
        plt.hist2d(locs[:, 1], locs[:, 2], bins=(bin_x_edges, bin_y_edges), cmap='magma', vmin=max_loc_dens * 0.1)
        for beam_idx, min_pos in enumerate(self.ebp.pos_mins_centered_nm):
            plt.scatter(*min_pos, color=self.ebp.psf_colors[beam_idx], s=100)
        plt.xlim(self.x_plot_range)
        plt.ylim(self.y_plot_range)
        # Annotations
        plt.gca().set_aspect('equal'), plt.xlabel('x (nm)'), plt.ylabel('y (nm)'), plt.tight_layout()
        plt.show()
        
    def plot_locs_withcrb(self, locs):
        """
        This function plots the localizations superimposed with the CRB map
        """
        # Create the CRB plot with the same extent as the scatter plots
        plt.figure('CRB_map with loalizations')
        # Shift CRB map by the same amount as the EBP
        plt.imshow(
            self.σ_CRB, cmap='viridis', vmin=0, vmax=20,
            extent=(
                - self.ebp.pos_mins_nm[0][0] - 0.5, self.σ_CRB.shape[1] - self.ebp.pos_mins_nm[0][0] - 0.5,
                - self.ebp.pos_mins_nm[0][1] - 0.5, self.σ_CRB.shape[0] - self.ebp.pos_mins_nm[0][1] - 0.5
            ),
            origin='lower'
        )
        plt.colorbar(label='σ_CRB Value')

        # Plot PSF minima positions with the same color mapping as before
        for beam_idx, min_pos in enumerate(self.ebp.pos_mins_centered_nm):
            plt.scatter(*min_pos, color=self.ebp.psf_colors[beam_idx], s=100)

        # add localizations to plot
        plt.scatter(locs[:, 1], locs[:, 2], c='gray', s=20, alpha=0.05)
        
        # Ensure the axes and aspect ratio are the same as in scatter plots
        plt.gca().set_aspect('equal')
        plt.xlim(self.x_plot_range)
        plt.ylim(self.y_plot_range)
        plt.xlabel('x (nm)')
        plt.ylabel('y (nm)')
        plt.title('σ_CRB with Aligned Reference Frame')
        plt.tight_layout()
        plt.show()
        
class ClockOrigamiAnalysis():
    def __init__(self, post_proc_data: DataPostProcessor, locs_filepath: Path, tcspc_data_dir: Path):
        self.post_proc_data = post_proc_data
        self.locs_filepath = locs_filepath
        self.tcspc_data_dir = tcspc_data_dir
        self.x_plot_range, self.y_plot_range = self.post_proc_data.get_glob_plots_limits(self.post_proc_data.locs_centered)
        self.center_of_locs, self.locs_zeroavg = self.recenter_locs(self.post_proc_data.locs_centered)
        self.fit_andplot_clockaxis(self.post_proc_data.locs_centered)
        self.locs_zeroavg_rotated = self.rotate_locs(self.locs_zeroavg, self.axis_slope)
        self.plot_loc_trace(self.locs_zeroavg_rotated)
        self.hidden_states, self.hidden_states_rescaled = self.hmm_fit(self.locs_zeroavg_rotated)
        self.locs_hmmfilt = self.hmm_filter(self.post_proc_data.locs_centered, self.hidden_states)
        # repeat fits with HMM-filtered data
        self.post_proc_data.plot_locs_withcrb(self.locs_hmmfilt)
        self.post_proc_data.plot_loc_density_withebp(self.locs_hmmfilt)
        # fit clouds of points
        self.fit_clock_clouds(self.locs_hmmfilt)

    def recenter_locs(self, locs):
        """
        This function recenter localizations with respect their center of mass
        """
        locs_recenter = copy.deepcopy(locs)
        center_of_locs = (np.mean(locs[:, 1]), np.mean(locs[:, 2]))
        locs_recenter[:, 1] -= center_of_locs[0]
        locs_recenter[:, 2] -= center_of_locs[1]
        return center_of_locs, locs_recenter
        
    def fit_andplot_clockaxis(self, locs):
        """
        This function performs gets the axis of the clock origami
        """
        # now perform Singular Value Decomposition analysis to find axis
        _, _, Vt = np.linalg.svd(self.locs_zeroavg[:, 1:3])
        main_axis = Vt[0]
        self.axis_slope = main_axis[1] / main_axis[0]
        axis_x = np.linspace(self.x_plot_range[0], self.x_plot_range[1], 100)
        axis_y = (axis_x - self.center_of_locs[0]) * self.axis_slope + self.center_of_locs[1]
        plt.figure('Clock axis plot')
        for beam_idx, min_pos in enumerate(self.post_proc_data.ebp.pos_mins_centered_nm):
            plt.scatter(*min_pos, color=self.post_proc_data.ebp.psf_colors[beam_idx], s=100)
        plt.scatter(locs[:, 1], locs[:, 2], c='gray', s=20, alpha=0.05)
        plt.plot(axis_x, axis_y, c='red', linestyle='--', linewidth=2)
        plt.xlim(self.x_plot_range)
        plt.ylim(self.y_plot_range)
        # Annotations
        plt.gca().set_aspect('equal'), plt.xlabel('x (nm)'), plt.ylabel('y (nm)'), plt.tight_layout()
        plt.show()
        
    def rotate_locs(self, locs, axis_slope):
        """
        This function returns the localizations in a new system of reference rotated accoridng to a given new x axis
        """
        self.rot_angle = np.arctan(axis_slope)
        rotated_locs = copy.deepcopy(locs)
        rotated_locs[:, 1] = locs[:, 1] * np.cos(self.rot_angle) + locs[:, 2] * np.sin(self.rot_angle)
        rotated_locs[:, 2] = - locs[:, 1] * np.sin(self.rot_angle) + locs[:, 2] * np.cos(self.rot_angle)
        return rotated_locs
    
    def plot_loc_trace(self, locs):
        """
        This function 
        """
        plt.figure("Localizations x time trace")
        plt.plot(locs[:, 0], locs[:, 1], label='x (nm)')
        plt.xlabel('Time (s)')
        plt.ylabel('Localizations (nm)')
        plt.title('')
        plt.legend()
        plt.grid(True)
        plt.show()
        
        plt.figure("Localizations y time trace")
        plt.plot(locs[:, 0], locs[:, 2], label='y (nm)')
        plt.xlabel('Time (s)')
        plt.ylabel('Localizations (nm)')
        plt.title('')
        plt.legend()
        plt.grid(True)
        plt.show()
        
    def hmm_fit(self, locs):
        """
        This function implements a basic HMM fit of the time trace and plots the rescaled prediciton for the hidden states
        """
        model = GaussianHMM(n_components=2, covariance_type="full", n_iter=1000)
        model.fit(locs[:, 1].reshape(-1, 1))
        hidden_states = model.predict(locs[:, 1].reshape(-1, 1))
        locs_statezero = locs[hidden_states == 0]
        locs_stateone = locs[hidden_states == 1]
        self.avg_statezero = np.mean(locs_statezero[:, 1])
        self.avg_stateone = np.mean(locs_stateone[:, 1])
        downstate_idx = np.argmin((self.avg_statezero, self.avg_stateone))
        if downstate_idx == 0:    
            hidden_states_rescaled = hidden_states * abs(self.avg_stateone - self.avg_statezero) + np.min((self.avg_stateone, self.avg_statezero))
        else:
            hidden_states_rescaled = (1 - hidden_states) * abs(self.avg_stateone - self.avg_statezero) + np.min((self.avg_stateone, self.avg_statezero))
        plt.figure(figsize=(12, 6))
        plt.plot(locs[:, 1], label="Localization Trace")
        plt.plot(hidden_states_rescaled, label="Predicted Hidden States", linestyle='--', color='red')
        plt.legend()
        plt.show()
        # prepare array with rotated localizations and HMM result (rescaled)
        self.rotated_clock_trace = np.empty((len(locs[:, 0]), 3), dtype=float)
        self.rotated_clock_trace[:, 0] = locs[:, 0]
        self.rotated_clock_trace[:, 1] = locs[:, 0]
        self.rotated_clock_trace[:, 2] = hidden_states_rescaled
        self.trace_hmm_filename = self.locs_filepath.stem + '_timetracewHMM.npy'
        self.trace_hmm_filepath = self.tcspc_data_dir / self.trace_hmm_filename
        np.save(self.trace_hmm_filepath, self.rotated_clock_trace)
        return hidden_states, hidden_states_rescaled
        
    def hmm_filter(self, locs, hidden_states):
        """
        This function finds all hidden state transitions and filters data based on this, throwing all
        localizations right before and right after a jump
        """
        locs_beforefilt = len(locs)
        locs_hmmfilt = locs[:-1][
            np.logical_and(
                np.isclose(np.diff(hidden_states), 0, atol=1e-6),
                np.isclose(np.diff(np.concatenate([hidden_states[:1], hidden_states[:-1]])), 0, atol=1e-6)
            )
        ] 
        locs_afterfilt = len(locs_hmmfilt)
        print(f"HMM filtering discarded {locs_beforefilt - locs_afterfilt} localizations")
        print(f"{locs_afterfilt} localizations remaining ({int(locs_afterfilt / locs_beforefilt * 100)}%)")
        
        self.locs_hmmfilts_filename = self.locs_filepath.stem + '_HMMfilt.npy'
        self.locs_hmmfilts_filepath = self.tcspc_data_dir / self.locs_hmmfilts_filename
        np.save(self.locs_hmmfilts_filepath, locs_hmmfilt)
        return locs_hmmfilt
    
    def fit_clock_clouds(self, locs):
        """
        This function uses a clustering algorithm to fit the two clouds of points of the clock
        """
        gmm = GaussianMixture(n_components=2, covariance_type='full')
        gmm.fit(locs[:, 1:3])  # Fit on (x, y) coordinates

        # Extract means and covariances
        means = gmm.means_  # Shape (2, 2), centers of the Gaussians
        covariances = gmm.covariances_  # Shape (2, 2, 2), full covariance matrices

        # Compute standard deviations (σ) from covariance matrix
        sigmas = np.sqrt(np.array([np.diag(cov) for cov in covariances]))
        for gauss_idx in range(2):
            print(f"Cloud number {gauss_idx}:")
            print(f"Center: {means[gauss_idx]}")
            print(f"Sigma: {sigmas[gauss_idx]}")
            
        print(f"Estimated clock origami size: {np.sqrt((means[0][0] - means[1][0])**2 + (means[0][1] - means[1][1])**2)}")
            

if __name__ == "__main__":
    # Open fitted experimental PSFs
    ebp = EBP(psf_dir)
    # look for pre-existing result files
    locs_filepath_list = []
    for filepath in natsorted(data_dir.iterdir()):
        if filepath.is_file():
            if (tcspc_filename.split('.')[0] in filepath.name) and (LOCS_FILE_SUFFIX in filepath.name):
                locs_filepath_list.append(filepath)
    if locs_filepath_list:
        print("Result files found:")
        for filenumber, filepath in enumerate(locs_filepath_list):
            print(f"{filenumber}. {filepath.name}")
        use_existing_result_file_choice = input("Do you want to use an existing result file? (y/n) ")
        if use_existing_result_file_choice == 'y':
            result_filenumber_chosen = int(input("Insert number of the result file to be used: "))
    if (not locs_filepath_list) or (use_existing_result_file_choice == 'n'):
        if not locs_filepath_list:
            print("No previous result file found...")
        print("Executing full analysis.")
        # execute full analysis if no previous result file is found
        tcspc_data = TCSPCData(tcspc_file, bckg_file, timetrace_bin_width_s, τ)
        minflux_analysis = MINFLUXAnalysis(ebp, tcspc_data, target_n_ph)
        locs_filepath_list.append(minflux_analysis.locs_results_filepath)
        result_filenumber_chosen = -1
    locs_dens_hist_bin_size = 1
    postproc = DataPostProcessor(locs_filepath_list[result_filenumber_chosen], ebp, locs_dens_hist_bin_size)
    clock_analysis_choice = input("Do you want to perform the analysis for the clock origami? (y/n) ")
    if clock_analysis_choice == 'y':
        clock_analysis = ClockOrigamiAnalysis(postproc, locs_filepath_list[result_filenumber_chosen], data_dir)

