# -*- coding: utf-8 -*-
"""
Created on Wed Nov 13 17:33:49 2024

Author: Lucía Lopez
Florencia D. Choque 
Description:
This script processes experimental pMINFLUX data using fitted point spread functions (PSFs) and TCSPC data.
At this stage, the MINFLUX excitation pattern has already been aligned, and the distances between the minima of the pattern 
have been confirmed to be good enough after a fitting process. 
This alignment and quality check are performed using `analise_EBP`, which operates on the raw PSFs generated by the MINFLUX setup.

Recommendations:
- Verify the τ parameter values, as they correspond to the peaks in the relative time histogram. 
Any hardware changes, such as swapping cables, may alter these values, potentially introducing errors. 
Future versions should automate this calibration to enhance robustness.

Details:
- An offset is applied to the relative time histogram peaks to match the acquisition order of the setup's PSFs.
- The `lifetime_win_i` and `lifetime_win_f` parameters specify the time window used for photon counting.

Note:
This code still requires adaptation for tracking experiments using Swabian hardware. But so far this is our working version.

"""

import os
import copy
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from matplotlib.patches import Ellipse
from PIL import Image
from natsort import natsorted
from pathlib import Path
from tools import tools_pMINFLUX as tools
from scipy.optimize import curve_fit
from scipy.stats import gaussian_kde
from configvar import (
    TCSPC_TIME_OFFSET_NS,
    LASER_PERIOD_NS,
    NUM_PULSE,
    STEP_NM,
    LIFETIME_WIN_BEG_NS,
    LIFETIME_WIN_END_NS,
    PSF_DIR_BASE,
    DATA_DIR_BASE
)

plt.close('all')


date = '20250214'
psf_dir = PSF_DIR_BASE / date
tcspc_file = DATA_DIR_BASE / date / 'clock_20250214-152357_.npy'
τ = np.array([0.98, 13.8, 26.12, 39.1])  # [ns] 
timetrace_bin_width_s = 0.1
target_n_ph = 1000

def gauss(x, a, mu, sigma):
    return a * np.exp(-((x - mu) ** 2) / (2 * sigma ** 2))

class EBP():
    def __init__(self, psf_dir: Path):
        self.psf_dir = psf_dir
        self.psf_colors = ['blue', 'orange', 'gray', 'yellow']
        self.psf_fits, self.pos_mins, self.pos_mins_centered = self.open_psf()
        self.plot_psf()

    def open_psf(self):
        """
        This function opens the specified data folder, reads in natural alphabetic order all the .npy
        files, which should contain the numpy arrays of the experimental PSFs, and loads them
        """
        psf_fit_list = []
        pos_min_list = []
        pos_min_centered_list = []
        for filepath in natsorted(self.psf_dir.iterdir()):
            if filepath.is_file():
                if filepath.suffix == '.npy':
                    psf_fit = np.load(filepath)
                    psf_fit_list.append(psf_fit)
                    psf_size = np.shape(psf_fit)[1]
                    self.size_nm = psf_size * STEP_NM
                    min_coords_fit_px = np.unravel_index(np.argmin(psf_fit, axis=None), psf_fit.shape)
                    min_coords_fit_px = (
                        min_coords_fit_px[1],
                        min_coords_fit_px[0]
                    )
                    min_coords_fit_nm = (
                        min_coords_fit_px[0] * STEP_NM,
                        min_coords_fit_px[1] * STEP_NM
                    )
                    pos_min_list.append(min_coords_fit_nm)
                    pos_min_centered_list.append(tools.indexToSpace(min_coords_fit_px, self.size_nm, STEP_NM))

        psf_fit_arr = np.array(psf_fit_list)
        pos_min_arr = np.array(pos_min_list)
        pos_min_centered_arr = np.array(pos_min_list)
        
        return psf_fit_arr, pos_min_arr, pos_min_centered_arr
    
    def plot_psf(self):
        """
        This function plots the individual experimental PSFs and the EBP
        """
        # Plot PSFs with minima positions
        fig, axes = plt.subplots(2, 2, figsize=(8, 8))
        for i, ax in enumerate(axes.flat):
            ax.set(xlabel = 'x (nm)', ylabel= 'y (nm)')
            ax.imshow(self.psf_fits[i], cmap='viridis', origin='lower')
            ax.scatter(*self.pos_mins[i],
                        color=self.psf_colors[i], s=100)
            ax.set_title(f'Fitted PSF {i + 1}', fontsize=10)
        plt.tight_layout()

        #Plot EBP
        x_min, y_min = self.pos_mins[:, 0], self.pos_mins[:, 1]
        plt.figure('EBP')
        for i in range(len(self.pos_mins)):
            plt.scatter(x_min[i]- self.pos_mins[0][0], y_min[i] - self.pos_mins[0][1], c=self.psf_colors[i], label=f'{i+1}')
        plt.title('EBP')
        plt.xlabel('x (nm)')
        plt.ylabel('y (nm)')
        plt.axhline(0, color='gray', linestyle='--', linewidth=0.5)
        plt.axvline(0, color='gray', linestyle='--', linewidth=0.5)
        plt.legend()
        plt.axis("equal")
        plt.grid(True)
        plt.show()

class TCSPCData():
    def __init__(self, ebp: EBP, tcspc_data_path: Path, timetrace_bin_width_s: float, τ: list):
        self.ebp = ebp
        self.tcspc_data_path = tcspc_data_path
        self.timetrace_bin_width_s = timetrace_bin_width_s
        self.τ = τ
        
        self.abs_time_s, self.rel_time_ps = self.load_tcspc_data()
        self.rel_time_ns = self.rel_time_ps * 1e-3
        self.tot_t_measuring = (self.abs_time_s.max() - self.abs_time_s.min())
        
        self.plot_timetrace()
        self.filter_time_data()
        self.shift_and_plot_tcspc_data()
        self.prep_ph_foranalysis()
        
    def load_tcspc_data(self):
        """
        This function loads the TCSPC data from a .npy file, loading both the absolute and relative times
        of the events
        """
        all_data = np.load(self.tcspc_data_path)
        rel_time_ps = all_data[2,:]
        abs_time_ps_woffset = all_data[1,:]
        abs_time_s = (abs_time_ps_woffset - abs_time_ps_woffset.min()) / 1e12 # ps to s and eliminate offset
        return abs_time_s, rel_time_ps

    def plot_timetrace(self):
        """
        This function plots the intensity time trace of the measurement
        """
        plt.figure("Histogram abs_time")
        self.raw_timetrace_bin_edges = np.arange(0, self.tot_t_measuring + self.timetrace_bin_width_s, self.timetrace_bin_width_s)
        self.raw_timetrace_counts_hz, _, _ = plt.hist(self.abs_time_s, bins=self.raw_timetrace_bin_edges, alpha=0.7, color='blue', weights=np.ones_like(self.abs_time_s) / self.timetrace_bin_width_s)
        plt.xlabel("Time [s]")
        plt.ylabel("Counts [Hz]")
        plt.title("Time trace")
        plt.tight_layout()
        plt.show()
        
    def filter_time_data(self):
        """
        This function asks the user the start and end time and the intensity threshold to select the relevant part of the measurement
        to be analysed, and filter all the data using these parameters and the relative time windows.
        Based on this information, it automatically identifies the bleaching step as the last moment the molecule goes below
        the intensity threshold and never recovers, and computes the background counts and average SBR.
        """
        start_t_input = input("Start time for analysis in s (input nothing for 0): ")
        if not start_t_input:
            self.start_t_s = 0.0
        else:
            self.start_t_s = float(start_t_input)
        end_t_input = input("End time for analysis in s (input nothing for end of the trace): ")
        if not end_t_input:
            self.end_t_s = self.tot_t_measuring
        else:
            self.end_t_s = float(end_t_input)
        int_threshold = float(input("Intensity threshold for signal in Hz: "))
        
        # find all the bin (left) edges where the molecule intensity is below the threshold
        dark_bin_edges = self.raw_timetrace_bin_edges[:-1][self.raw_timetrace_counts_hz < int_threshold]
        # compute times until two nearest dark bins. The n-th element is the time between the (n-1)-th and the n-th dark bin
        t_tonext_dark_bin = np.concatenate(([dark_bin_edges[0]], np.diff(dark_bin_edges)))
        # find the first bin of each dark period of the molecule
        start_dark_time = dark_bin_edges[t_tonext_dark_bin > (self.timetrace_bin_width_s * 1.5)]
        # the bleaching step is selected as the last time the molecule goes dark and never recovers
        self.bleach_t_s = start_dark_time[-1]
        print(f"Molecule photobleached after {self.bleach_t_s} s")
        # here we compute the emitter and background counts and the estimated SBR
        self.emitter_stop_t_s = self.bleach_t_s - self.timetrace_bin_width_s
        self.bckg_start_t_s = self.bleach_t_s + self.timetrace_bin_width_s
        self.filt_rel_time_ns = self.rel_time_ns[np.logical_and(
            self.abs_time_s > self.start_t_s,
            self.abs_time_s < np.min((self.end_t_s, self.emitter_stop_t_s))
        )]
        self.filt_rel_time_bckg_ns = self.rel_time_ns[np.logical_and(
            self.abs_time_s > self.bckg_start_t_s,
            self.abs_time_s < self.end_t_s
        )]
        self.filt_abs_time_s = self.abs_time_s[np.logical_and(
            self.abs_time_s > self.start_t_s,
            self.abs_time_s < np.min((self.end_t_s, self.emitter_stop_t_s))
        )]
        self.bckg_abs_time_s = self.abs_time_s[np.logical_and(
                self.abs_time_s > self.bckg_start_t_s,
                self.abs_time_s < self.end_t_s
        )]
        self.photons_tokeep = len(self.filt_abs_time_s)
        print(f"The molecule emitted {self.photons_tokeep} photons in the relevant part of the measurement")
        self.avg_bckg_counts = (len(self.bckg_abs_time_s) / (self.end_t_s - self.bckg_start_t_s))
        self.avg_emitter_counts = self.photons_tokeep / (self.emitter_stop_t_s - self.start_t_s) - self.avg_bckg_counts
        self.avg_sbr = self.avg_emitter_counts / self.avg_bckg_counts
        print("*****************************")
        print("Measure parameters before TCSPC timegating and considering all pulses:")
        print(f"Average signal counts: {self.avg_emitter_counts - self.avg_bckg_counts} Hz")
        print(f"Average background counts: {self.avg_bckg_counts} Hz")
        print(f"Average SBR for all pulses: {self.avg_sbr}")
        print("*****************************")
        
    def shift_and_plot_tcspc_data(self):
        """
        This function plots the decay curves of the TCSPC data, with and without translation, and the time windows used for analysis.
        """
        # shift TCSPC data (filtered, unfiltered and background) to put first pulse close to 0
        self.rel_time_shift_ns = (self.rel_time_ns - TCSPC_TIME_OFFSET_NS) % LASER_PERIOD_NS
        self.filt_rel_time_shift_ns = (self.filt_rel_time_ns - TCSPC_TIME_OFFSET_NS) % LASER_PERIOD_NS
        self.bckg_rel_time_shift_ns = (self.filt_rel_time_bckg_ns - TCSPC_TIME_OFFSET_NS) % LASER_PERIOD_NS
        
        plt.figure('Emitter TCSPC Histogram')
        plt.hist(self.filt_rel_time_shift_ns, bins = 300, range=(0,50), label='arrival time (shifted)', alpha=0.7)
        for tau in τ:
            plt.axvline(tau, color='red', linestyle='--')
            plt.axvspan(tau + LIFETIME_WIN_BEG_NS, tau + LIFETIME_WIN_END_NS, color='red', alpha=0.2)
        plt.xlabel('Time [ns]')
        plt.ylabel('Counts')
        plt.legend()
        plt.tight_layout()
        plt.show()
        
        plt.figure('Background TCSPC Histogram')
        plt.hist(self.bckg_rel_time_shift_ns, bins = 300, range=(0,50), label= 'arrival time (shifted)', alpha=0.7)
        for tau in τ:
            plt.axvline(tau, color='red', linestyle='--')
            plt.axvspan(tau + LIFETIME_WIN_BEG_NS, tau + LIFETIME_WIN_END_NS, color='red', alpha=0.2)
        plt.xlabel('Time [ns]')
        plt.ylabel('Counts')
        plt.legend()
        plt.tight_layout()
        plt.show()
        
    def prep_ph_foranalysis(self):
        """
        This function prepares, for each pulse, an array of absolute times keeping only the photons in the TCSPC timegating window
        which will be used for analysis. Also, it computes the corrected background counts and sbr, for each pulse and using this timegating
        """
        self.abs_time_s_foranalysis_perpulse = []
        self.emitter_counts_perpulse = []
        self.allpulses_tot_counts_timegated = 0
        self.allpulses_emitter_counts_timegated = 0
        self.allpulses_bckg_counts_timegated = 0
        self.bckg_counts_perpulse = []
        self.sbr_perpulse = []
        for pulse_idx in range(NUM_PULSE):
            # computing start and end of the time window used for timegating for the current pulse
            start_win = τ[pulse_idx] + LIFETIME_WIN_BEG_NS
            end_win = τ[pulse_idx] + LIFETIME_WIN_END_NS
            # selecting all the photons used for analysis for the current pulse
            abs_time_s_foranalysis = self.filt_abs_time_s[
                np.logical_and(
                    self.filt_rel_time_shift_ns > start_win,
                    self.filt_rel_time_shift_ns < end_win,
                )
            ]
            # appending (important: a deepcopy!) of the obtained array to the list
            self.abs_time_s_foranalysis_perpulse.append(copy.deepcopy(abs_time_s_foranalysis))
            # now doing the same with the background to get the correct background counts
            bckg_counts_timegated = len(self.bckg_abs_time_s[
                np.logical_and(
                    self.bckg_rel_time_shift_ns > start_win,
                    self.bckg_rel_time_shift_ns < end_win,
                )
            ]) / (self.end_t_s - self.bckg_start_t_s)
            self.bckg_counts_perpulse.append(bckg_counts_timegated)
            self.emitter_counts_perpulse.append(
                len(abs_time_s_foranalysis) / (self.emitter_stop_t_s - self.start_t_s) - bckg_counts_timegated
            )
            self.sbr_perpulse.append(self.emitter_counts_perpulse[pulse_idx] / self.bckg_counts_perpulse[pulse_idx])
            
        print("*****************************")
        print("Measure parameters after TCSPC timegating and per pulse:")
        for pulse_idx in range(NUM_PULSE):
            print(f"Signal counts for pulse {pulse_idx}: {self.emitter_counts_perpulse[pulse_idx]} Hz")
            self.allpulses_emitter_counts_timegated += self.emitter_counts_perpulse[pulse_idx]
            print(f"Background counts for pulse {pulse_idx}: {self.bckg_counts_perpulse[pulse_idx]} Hz")
            self.allpulses_bckg_counts_timegated += self.bckg_counts_perpulse[pulse_idx]
            self.allpulses_tot_counts_timegated = self.allpulses_emitter_counts_timegated + self.allpulses_bckg_counts_timegated
            print(f"SBR  for pulse {pulse_idx}: {self.sbr_perpulse[pulse_idx]}")
        print(f"Signal counts for all pulses used for analysis: {self.allpulses_emitter_counts_timegated}")
        print(f"Background counts for all pulses: {self.allpulses_bckg_counts_timegated}")
        print("*****************************")
     
    def plot_crb(self):
        """
        This function computes the crb based on the sbr we just computed and the time binning used for the time trace
        """
        # CRB Calculation and Plot
        σ_CRB = tools.crb_minflux(NUM_PULSE, self.ebp.psf_fits, np.mean(self.avg_sbr), STEP_NM, self.ebp.size_nm, np.mean(self.avg_emitter_counts), method='1')

        # Create the CRB plot with the same extent as the scatter plots
        plt.figure('CRB_map')
        plt.imshow(σ_CRB, cmap='viridis', vmin=0, vmax=20)
        plt.colorbar(label='σ_CRB Value')

        # Plot PSF minima positions with the same color mapping as before
        for i, p in enumerate(self.ebp.pos_mins):
            plt.scatter(*np.unravel_index(np.argmin(self.ebp.psf_fits[i]), self.ebp.psf_fits[i].shape)[::-1], 
                        color=self.ebp.psf_colors[i], s=100)

        # Ensure the axes and aspect ratio are the same as in scatter plots
        plt.gca().set_aspect('equal')
        plt.xlabel('x (nm)')
        plt.ylabel('y (nm)')
        plt.title('σ_CRB with Aligned Reference Frame')
        plt.tight_layout()

class MINFLUXAnalysis():
    def __init__(self, tcspc_data: TCSPCData, target_n_ph: int):
        self.tcspc_data = tcspc_data
        self.target_n_ph = target_n_ph
        self.choose_locs_t_binning()
        
    def choose_locs_t_binning(self):
        target_locs_t_binning_s = float(self.target_n_ph) / self.tcspc_data.allpulses_tot_counts_timegated
        print(f"Localization time binning (in s) to obtain {self.target_n_ph} photons per bin: {target_locs_t_binning_s}")
        self.locs_t_binning_s = float(input("Choose localization time binning (in s): "))
        self.avg_n_ph_perloc = self.tcspc_data.allpulses_tot_counts_timegated * self.locs_t_binning_s
        print(f"Average number of photons per localization: {self.avg_n_ph_perloc}")
        
    
        

if __name__ == "__main__":
    # Open fitted experimental PSFs
    ebp = EBP(psf_dir)
    tcspc_data = TCSPCData(ebp, tcspc_file, timetrace_bin_width_s, τ)
    minflux_analysis = MINFLUXAnalysis(tcspc_data, target_n_ph)

# Estimate Positions
counts_each_bin = float(input("Ingresa counts totales por bin: "))
counts_bkg_each_bin = float(input("Ingresa counts de bkg por bin: "))

background_rate = counts_bkg_each_bin//time_each_bin #Hz
signal_rate = counts_each_bin/time_each_bin #Hz
locs_t_binning_s = 0.06 #[s]
print("Signal_rate: ", signal_rate, "Hz")
print("Background rate: ", background_rate, "Hz")
print("SBR aprox: ", (signal_rate - background_rate)/background_rate)
nbins = int(((abs_time.max()- abs_time.min())/1E12)// locs_t_binning_s)
bin_size = len(rel_time_new)//nbins
print("nbins: ", nbins)
print('bin_size: ', bin_size)
r0_est_nm, N, SBR = np.zeros((2, nbins)), np.zeros(nbins), np.zeros(nbins)

for i in range(nbins):
    window = rel_time_new[i * bin_size:(i + 1) * bin_size]
    SBR[i] = len(window) / (locs_t_binning_s * background_rate)
    n_array = tools.n_minflux(τ, window, LIFETIME_WIN_BEG_NS, LIFETIME_WIN_END_NS)
    N[i] = np.sum(n_array)
    _, r0_est_nm[:, i], _ = tools.pos_minflux(n_array, psf_fit_arr, SBR[i], STEP_NM) #Already in nm, check pos_minflux
print(f"<N> = {np.round(np.mean(N),0)}")
x_loc, y_loc = r0_est_nm[0] - pos_min_arr[0][0], r0_est_nm[1] - pos_min_arr[0][1] #Le resto esto porque es la referencia alrededor de la que quiero dibujar.
meanx, meany = np.mean(x_loc), np.mean(y_loc)
sigmax, sigmay = np.std(x_loc), np.std(y_loc)
#%% Localizations
plt.figure('Localizations')
for i, p in enumerate(pos_min_arr):
    plt.scatter(*(p - pos_min_arr[0]), color=colors[i], s=100)
plt.scatter(x_loc, y_loc, c='gray', s=20, alpha=0.25)
plt.scatter(np.mean(x_loc), np.mean(y_loc), color='black', marker='+')
# Annotations
plt.annotate(f'<x> = {meanx:.2f} nm', xy=(0.05, 0.80), xycoords='axes fraction', fontsize=8, color='blue', verticalalignment='top')
plt.annotate(f'<y> = {meany:.2f} nm', xy=(0.05, 0.75), xycoords='axes fraction', fontsize=8, color='blue', verticalalignment='top')
plt.annotate(f'σx = {sigmax:.2f} nm', xy=(0.05, 0.95), xycoords='axes fraction', fontsize=8, color='blue', verticalalignment='top')
plt.annotate(f'σy = {sigmay:.2f} nm', xy=(0.05, 0.90), xycoords='axes fraction', fontsize=8, color='blue', verticalalignment='top')
plt.gca().set_aspect('equal'), plt.xlabel('x (nm)'), plt.ylabel('y (nm)'), plt.tight_layout()

# Scatter Plot with Time Encoding
plt.figure('Localizations_time_encoding')
for i, p in enumerate(pos_min_arr):
    plt.scatter(*(p - pos_min_arr[0]), color=colors[i], s=100)
plt.scatter(x_loc, y_loc, c=range(len(x_loc)), cmap='rainbow', s=20)
plt.gca().set_aspect('equal'), plt.colorbar(label='Time encoding')
plt.xlabel('x (nm)'), plt.ylabel('y (nm)'), plt.tight_layout()

ax = plt.gca()
ax.get_xlim()
ax.get_ylim()
#%% KDE plot
x_min, x_max = np.min(x_loc), np.max(x_loc)
y_min, y_max = np.min(y_loc), np.max(y_loc)

x_grid = np.linspace(x_min, x_max, 300)
y_grid = np.linspace(y_min, y_max, 300)
X, Y = np.meshgrid(x_grid, y_grid)

positions = np.vstack([X.ravel(), Y.ravel()])
values = np.vstack([x_loc, y_loc])
kde = gaussian_kde(values, bw_method=0.1)
Z = np.reshape(kde(positions), X.shape)

plt.figure('Localization Density')
plt.imshow(Z, origin='lower', extent=[x_min, x_max, y_min, y_max], cmap='hot', aspect='auto')
plt.colorbar(label="Density")
#plt.scatter(x_loc, y_loc, c='gray', s=5, alpha=0.25)  #
plt.xlabel('x (nm)')
plt.ylabel('y (nm)')
plt.title('Density of Localizations, , <N> = {np.mean(N)}')
plt.show()

#%% Pocos outliers Revisar si conviene usar esta manera
# # Calculo de percentiles 5 y 95 para evitar valores extremos
# p5, p95 = np.percentile(x_loc, [5, 95])

# umbral_x = (p5 + p95) / 2

# # Filtro de datos en dos nubes
# nube1_mask = x_loc < umbral_x  # Nube izquierda
# nube2_mask = x_loc >= umbral_x  # Nube derecha

# x_nube1, y_nube1 = x_loc[nube1_mask], y_loc[nube1_mask]
# x_nube2, y_nube2 = x_loc[nube2_mask], y_loc[nube2_mask]

# # Calcular estadísticas de cada nube
# meanx1, meany1 = np.mean(x_nube1), np.mean(y_nube1)
# sigmax1, sigmay1 = np.std(x_nube1), np.std(y_nube1)

# meanx2, meany2 = np.mean(x_nube2), np.mean(y_nube2)
# sigmax2, sigmay2 = np.std(x_nube2), np.std(y_nube2)

# print(f"Nube 1: <x> = {meanx1:.2f} nm, <y> = {meany1:.2f} nm, σx = {sigmax1:.2f} nm, σy = {sigmay1:.2f} nm")
# print(f"Nube 2: <x> = {meanx2:.2f} nm, <y> = {meany2:.2f} nm, σx = {sigmax2:.2f} nm, σy = {sigmay2:.2f} nm")

#%% 3 Sigmas
#Creo que elijo esta forma, revisar si es lo mejor
mean_x = np.mean(x_loc)
std_x = np.std(x_loc)

#Límites basado en 3 sigmas
lim_inf, lim_sup = mean_x - 3 * std_x, mean_x + 3 * std_x

# Filtro
mask_valid = (x_loc > lim_inf) & (x_loc < lim_sup)
x_clean, y_clean = x_loc[mask_valid], y_loc[mask_valid]

# Método del umbral con percentiles
p5, p95 = np.percentile(x_clean, [5, 95])
umbral_x = (p5 + p95) / 2

nube1_mask = x_clean < umbral_x
nube2_mask = x_clean >= umbral_x

x_nube1, y_nube1 = x_clean[nube1_mask], y_clean[nube1_mask]
x_nube2, y_nube2 = x_clean[nube2_mask], y_clean[nube2_mask]

meanx1, meany1 = np.mean(x_nube1), np.mean(y_nube1)
sigmax1, sigmay1 = np.std(x_nube1), np.std(y_nube1)
meanx2, meany2 = np.mean(x_nube2), np.mean(y_nube2)
sigmax2, sigmay2 = np.std(x_nube2), np.std(y_nube2)

print(f"Nube 1: <x> = {meanx1:.2f} nm, <y> = {meany1:.2f} nm, σx = {sigmax1:.2f} nm, σy = {sigmay1:.2f} nm")
print(f"Nube 2: <x> = {meanx2:.2f} nm, <y> = {meany2:.2f} nm, σx = {sigmax2:.2f} nm, σy = {sigmay2:.2f} nm")

#%% Trace bins
bins_num=range(0,len(x_loc))
plt.figure('Trace')
plt.plot(bins_num, x_loc, label='x', alpha=0.8) #, marker='o', markersize=4)
plt.plot(bins_num, y_loc, label='y', alpha=0.8) #, marker='o', markersize=4)

plt.xlabel('bins')
plt.ylabel('Localizations')
plt.title('Time trace')
plt.legend()
plt.grid(True)
plt.show()
#%% Trace localizations - Analyse clouds
time_seconds_binned = np.array([np.mean(abs_time[i * bin_size : (i + 1) * bin_size]) for i in range(nbins)])  
time_seconds_binned = (time_seconds_binned - abs_time.min()) / 1E12
plt.figure("Time Trace")
plt.plot(time_seconds_binned, x_loc, label='x (nm)', marker='o', markersize=4, alpha=0.8)
plt.plot(time_seconds_binned, y_loc, label='y (nm)', marker='o', markersize=4, alpha=0.8)
plt.xlabel('Time (s)')
plt.ylabel('Localizations (nm)')
plt.title('')
plt.legend()
plt.grid(True)
plt.show()

definir_nubes = True
nube_ranges = []
while definir_nubes:
    try:
        start_bin = int(input("Ingrese el bin de inicio de la nube (o -1 para terminar): "))
        if start_bin == -1:
            break
        end_bin = int(input("Ingrese el bin de fin de la nube: "))
        nube_ranges.append((start_bin, end_bin))
    except ValueError:
        print("Por favor, ingrese valores enteros válidos.")

for i, (start, end) in enumerate(nube_ranges):
    x_nube = x_loc[start:end]
    y_nube = y_loc[start:end]
    
    mean_x, std_x = np.mean(x_nube), np.std(x_nube)
    mean_y, std_y = np.mean(y_nube), np.std(y_nube)
    
    print(f"Nube {i+1}: Bins {start} - {end}")
    print(f"  Media X: {mean_x:.2f} nm, Desviación X: {std_x:.2f} nm")
    print(f"  Media Y: {mean_y:.2f} nm, Desviación Y: {std_y:.2f} nm")
    
    plt.figure(f"Nube {i+1}")
    plt.scatter(x_nube, y_nube, c=range(len(x_nube)), cmap='rainbow', s=20)
    plt.xlabel('x (nm)')
    plt.ylabel('y (nm)')
    plt.title(f'Nube {i+1} de Localizaciones')
    plt.colorbar(label='Orden Temporal')
    plt.grid(True)
    plt.show()
    
    #Gaussian fit
    hist, bin_edges = np.histogram(x_nube, bins=30, density=True)
    bin_centers = (bin_edges[:-1] + bin_edges[1:]) / 2

    popt, pcov = curve_fit(gauss, bin_centers, hist, p0=[1, np.mean(x_nube), np.std(x_nube)])
    a_fit, mu_fit, sigma_fit = popt

    plt.figure()
    x = np.linspace(min(x_nube), max(x_nube), 1000)
    plt.hist(x_nube, bins=30, density=True, alpha=0.6, color='g', label='Data')
    plt.plot(x, gauss(x, *popt), 'r-', label=r'Gaussian\n$\mu={mu_fit:.2f}, \sigma={sigma_fit:.2f}$')
    plt.xlabel('x (nm)')
    plt.ylabel('Density')
    plt.legend()
    plt.title(f'Gaussian fit x locs in Cloud {i}')
    plt.show()

    hist, bin_edges = np.histogram(y_nube, bins=30, density=True)
    bin_centers = (bin_edges[:-1] + bin_edges[1:]) / 2

    popt, pcov = curve_fit(gauss, bin_centers, hist, p0=[1, np.mean(y_nube), np.std(y_nube)])
    a_fit, mu_fit, sigma_fit = popt
    plt.figure()
    x = np.linspace(min(y_loc), max(y_loc), 1000)
    plt.hist(y_nube, bins=30, density=True, alpha=0.6, color='g', label='Data')
    plt.plot(x, gauss(x, *popt), 'r-', label=r'Gaussian\n$\mu={mu_fit:.2f}, \sigma={sigma_fit:.2f}$')
    plt.xlabel('y (nm)')
    plt.ylabel('Density')
    plt.legend()
    plt.title(f'Gaussian fit y locs in Cloud {i}')
    plt.show()

#%%
plt.figure('All Localizations with Ellipses')

# Colores para cada nube
colors = ['blue', 'orange', 'green', 'red', 'purple']

for i, (start_bin, end_bin) in enumerate(nube_ranges):
    x_nube = x_loc[start_bin:end_bin]
    y_nube = y_loc[start_bin:end_bin]
    
    meanx, meany = np.mean(x_nube), np.mean(y_nube)
    sigmax, sigmay = np.std(x_nube), np.std(y_nube) # Esto creo que no se está calculando bien
    print(f"Nube {i+1}: Bins {start} - {end}")
    print(f"  Media X: {meanx:.2f} nm, Desviación X: {sigmax:.2f} nm")
    print(f"  Media Y: {meany:.2f} nm, Desviación Y: {sigmay:.2f} nm")
    plt.scatter(x_nube, y_nube, color=colors[i % len(colors)], alpha=0.4, label=f'Nube {i+1}')

    elipse = patches.Ellipse((meanx, meany), 2 * sigmax, 2 * sigmay, edgecolor=colors[i % len(colors)], 
                              facecolor='none', linewidth=2, linestyle='--')
    plt.gca().add_patch(elipse)
    plt.scatter(meanx, meany, color=colors[i % len(colors)], marker='+', s=100)

plt.xlabel('x (nm)')
plt.ylabel('y (nm)')
plt.gca().set_aspect('equal')
plt.legend()
plt.title('Localizaciones de todas las nubes con elipses de dispersión')
plt.tight_layout()
plt.show()
#%% Análisis de nubes
def plot_ellipse_cov(mean, cov, ax, color='red', alpha=0.3):
    """Dibuja una elipse usando la covarianza."""
    vals, vecs = np.linalg.eigh(cov)
    width, height = 2 * np.sqrt(vals)  # Escala con desviaciones estándar
    angle = np.degrees(np.arctan2(*vecs[:, 1][::-1]))  # Orientación
    ell = Ellipse(xy=mean, width=width, height=height, angle=angle,
                  edgecolor=color, facecolor=color, alpha=alpha)
    ax.add_patch(ell)

def plot_ellipse_percentile(x, y, ax, color='blue', alpha=0.3):
    """Dibuja una elipse basada en percentiles del 68%."""
    mean_x, mean_y = np.mean(x), np.mean(y)
    perc_x, perc_y = np.percentile(x, [16, 84]), np.percentile(y, [16, 84])
    width, height = perc_x[1] - perc_x[0], perc_y[1] - perc_y[0]
    ell = Ellipse(xy=(mean_x, mean_y), width=width, height=height,
                  edgecolor=color, facecolor=color, alpha=alpha)
    ax.add_patch(ell)

fig, ax = plt.subplots(figsize=(6, 6))
colors = ['blue','cyan','green', 'orange','red']
for i, (start, end) in enumerate(nube_ranges):
    x_nube, y_nube = x_loc[start:end], y_loc[start:end]
    mean = [np.mean(x_nube), np.mean(y_nube)]
    cov = np.cov(x_nube, y_nube)
    ax.scatter(x_nube, y_nube, s=10, alpha=0.3, label=f'Nube {i+1}', color=colors[i])

    # Elipse basada en covarianza
    plot_ellipse_cov(mean, cov, ax, color=colors[i])

    # Elipse basada en percentiles
    plot_ellipse_percentile(x_nube, y_nube, ax, color='black')

ax.set_xlabel('x (nm)')
ax.set_ylabel('y (nm)')
ax.set_aspect('equal')
ax.legend()
plt.title('')
plt.show()
